### PR TITLE
Add page for xlet translations

### PR DESCRIPTION
**Pull request by fredcw**

### CODE REVIEW

**Comment by fredcw** [comment]
Here's what the page looks like, converted to .md. Perhaps this would be better as a tutorial on community.linuxmint.com?

Cinnamon xlets (applets, desklets and extensions)
=================================================

While the translations for the default xlets are done on Launchpad, the translations for third party xlets (the ones you have to download) are done in a different way.

To add translations for third party applets, desklets and extensions, you first need to make the changes to your local copy of the xlet, test your changes and then make a github "pull request" so that your changes can benefit other users of the xlet.

Let's say for instance that you want to add some translations for the Weather applet. First find where the applet is stored - in this case you'll find it at `~/.local/share/cinnamon/applets/weather@mockturtl`. In this directory is another directory called "po" where all the translations are found. There is a separate .po file for each language. These .po files are just text files which can be edited by hand in a text editor but most people use a program called poedit which is designed especially for editing these files. Poedit should be available in the software manager.

Using Poedit
------------

Once you've opened the relevant .po file in poedit, you first need to make sure that it is up to date and contains all the latest strings that need translating as it may not have been updated for a while. To do this, select Translation \> Update from POT File... in the menu and select the .pot file that is in the same directory as the .po file you are editing, in this case it's `weather@mockturl.pot`. You can now add your translations in poedit and save the file. Poedit may also save a .mo file in the same directory but this should be deleted. You can prevent poedit from saving a .mo file in the preferences.

Install the changes
-------------------

Once you've saved the file, you'll need to install it. Go to the directory containing the applet folder - in this case `~/.local/share/cinnamon/applets` and open a terminal. Enter the command:

``` {.sourceCode .bash}
cinnamon-xlet-makepot weather@mockturtl --install
```

or replace "weather@mockturtl" with the name of the folder containing the applet you've added translations to. It should say: "installed 20 files" or however many .po files the applet has. Now restart cinnamon (Ctrl-Alt-Esc) and see your translations in the applet.

> **note**
>
> More detailed instructions on this process (including instructions for applet developers) can be found [here](https://github.com/NikoKrause/CinnVIIStarkMenu/issues/19).

Once you're happy with your changes you can upload your changed .po file to github to share with others.

Upload to Github
----------------

Making changes on Github is slightly more complicated than uploading a file on a normal website but it's fairly easy once you understand the basic concept. Instead of just uploading a file, you first have to "fork" the "repository" to which you want to make changes. This effectively means that you create your very own exact copy of Linux Mint's repository that now belongs to your github account. You then make changes to your copy of the repository, e.g. uploading your new version of your .po file. When you're happy with the changes you've made, you then open a "pull request". This means that you're asking Linux Mint to "merge" or combine the changes you've made to your version of the repository with Linux Mint's version of the repository. Once your "pull request" has been accepted and merged by Linux Mint, you can then delete your copy of the repository ready to do the whole thing again when you want to make some more changes.

If all this seems a bit too complicated, you could always try emailing your updated .po file to the xlet's author and they will probably be happy to do this for you.

Using Github
------------

Lets say that you want to upload your new version of bg.po, the Bulgarian translation of the weather applet. Once you've created a github account, go to <https://github.com/linuxmint/cinnamon-spices-applets> and fork this respository.

github_fork

You should then have your own copy of this repository.

github_mainpage

In your fork of the repository, navigate to the folder containing the file you want to update and click on Add file \> Upload files or simply drag and drop your new file onto the page.

github_addfile

You will then be asked to "Commit changes". Add a comment and click the Commit changes button.

You have now updated the file in your repository. Now you can ask Linux Mint to merge your changes into their repository by opening a pull request.

github_pullrequest

You will then be presented with a page showing the changes you propose and a button to confirm the pull request Create pull request. Now give your pull request a title, e.g. "weather@mockturtl: update bg.po" and that's it. All you have to do now is wait for Linux Mint to review and merge your pull request. When this happens, you should receive an email, after which you can safely delete your fork ready for the next time. It's always a good idea to delete your fork when you no longer need it because if you accidentally fork the same repository twice, things can get complicated. You can delete your fork at the bottom of the settings page.

github_settings

**Comment by haggen88** [comment]
Thanks @fredcw, this has been a great help!

One question: If I want to send several PRs [the Guidelines for Contributing says One Pull Request - One Applet ... in my case they are translations], do I have to delete the Fork every time I send another PR? [after the merge of the last PR].

Context: I tried to submit a new PR to a repository and when I submitted it, commits from the old PR appeared. To avoid this I delete and create a new Fork and send a the new PR.

Regards

**Comment by fredcw** [comment]
@haggen88 Yes, there is a better way if you're making multiple PRs. Instead of making changes directly to your fork, you can create a new "branch" of your fork for each PR you want to make. Click on the button that says "master" and create a new branch:

Screenshot from 2021-12-06 04-40-18

You can use this same button to switch between different branches of your fork. When you're finished with a branch you can just delete that branch instead of the main (master) fork. 

After a while (days or weeks) other people may have made changes to linuxmint's repository and your fork may become outdated. Instead of deleting your fork and creating a new one, you can just click on Fetch upstream->Fetch and merge.

**Comment by haggen88** [comment]
@fredcw thank you very much for the information !

P.S.  I created another branch and tried to generate a new PR from that new branch. Even so the new PR considers past [commits](https://user-images.githubusercontent.com/68134588/144902053-1c438be7-21bb-4266-91c7-fced7e70e246.png), my fork mentions that "This branch is not behind the upstream", so I suppose I should wait for my previous PR to merge... right?

**Comment by fredcw** [comment]
@haggen88 Yes, if you have past PRs in your master branch then these will be included in your new branches. You can think of new branches as forks of your master branch. The thing to do is wait until the PR in your master branch is finished with, delete your whole fork and create a new fork, and from then on, only create new branches for each PR leaving the master branch unchanged and from which you can create new branches.

**Comment by fredcw** [comment]
I added this as a tutorial on community.linuxmint.com.

[How to add translations to cinnamon's 3rd party applets, desklets and extensions](https://community.linuxmint.com/tutorial/view/2521)

**Pull request closed without merging**
